
*** Squash commits
    #+begin_src sh
     git rebase -i HEAD~n
    #+end_src
    #(Replace n appropriately). 
    #Then, change pick to squash for the commits to be squashed.
    #From Howard Abrams' [[http://howardism.org/Technical/Git/squashing-commits.html][post]].

    #If there are only 2 commits to be squashed, it is much simpler to just do a reset.
    git reset --soft HEAD^^
    #The above command ignores the logs for those commits. To include the logs :
    git reset --soft HEAD~3 && git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"
    #Replace 3 appropriately
    #+end_src

*** Alias for git pull --rebase 
    git config --global alias.pull 'pull --rebase'

*** Show the top contributers to a package
    git shortlog -sne

*** Look at the type and contents of a blob or commit
    git cat-file -t <Blob or Commit  hash ID> -> This fetches the type of the object
    git cat-file <type>(blob, commit etc) <>  -> This shows the contents of the blob,tree or commit.
    
*** Fetch commit IDs for blobs/trees from a branch
    git ls-tree <branch-name> (for eg: git ls-tree HEAD)
